### ISSUE TITLE
Évolution: Formulaire de contact

### ISSUE THREAD

**Issue by PierreKrauseEpsi** [remihamy1/webapp#10]
### Description :
Ajout d'un formulaire de contact classique

### Détails : 
Le formulaire possèdes plusieurs champs : 
- Nom - Prénom
- Adresse mail
- (Sujet de la demande)
- Numéro des commandes (liste déroulante) : UNIQUEMENT si l'utilisateur est connecté
- Détails de la demande
- Bouton d'envois

Après l'envois de la demande, une pop-up de confirmation s'affiche.

### Bénéfices attendus : 
Possibilité de créer une demande d'aide.

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[BASSE]

**Comment by Florent-Deswaerte** [comment]
Fix résolu
