### ISSUE TITLE
Fix: Fermeture du détail d'un produit impossible à fermer 

### ISSUE THREAD

**Issue by MaXimeHH** [remihamy1/webapp#11]
### Détails du Produit
Page produit.
Produit – Fermeture du détail lié à un produit impossible

### Résumé

Lorsque le détail d'un produit est ouvert, c'est impossible de fermer le détail, la page doit être rafraîchie pour fermer le détail

### Étapes à reproduire

Se rendre sur la page "Produit"
Appuyer sur le nom du produit

### Résultat attendu

Avoir un bouton permettant de fermer le détail ou fermer le détail en appuyant hors du détail

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[MOYENNE]

**Comment by ShinWolf** [comment]
On est d'accord on réduit la taille de la modal ?

**Comment by NeoSylvr** [comment]
Aucune idée, je n'ai pas eu le temps de m'attarder sur le problème
________________________________
De : ShinWolf ***@***.***>
Envoyé : lundi 18 décembre 2023 14:15
À : remihamy1/webapp ***@***.***>
Cc : BONBON Rodrigue ***@***.***>; Assign ***@***.***>
Objet : Re: [remihamy1/webapp] Fix: Fermeture du détail d'un produit impossible à fermer (Issue #11)


On est d'accord on réduit la taille de la modal ?

**Comment by MaXimeHH** [comment]
Oui, il faut réduire la modal, la centré etc... comme fait le ng-model d'Angular

**Comment by ShinWolf** [comment]
Dans le doute je l'ai réduite car beaucoup trop grande

**Comment by Florent-Deswaerte** [comment]
Fix résolu
