### ISSUE TITLE
Évolution: Refonte de l'interface utilisateur

### ISSUE THREAD

**Issue by MaXimeHH** [remihamy1/webapp#16]
### Description

Il nous a été demandé de faire une refonte de l'application.

### Demandes

**Accueil**
Mettre les produits en avant (produit phare, POP mascotte...)

**Produits**
Afficher tous les produits proposés

### Contraintes
Aucunes contraintes côté client.
Le choix des polices, des couleurs ainsi que des images est complètement libre

### Points d'attention 
Ce site est destiné principalement à un public de passionnés (collectionneurs) et qui aime l'art des pop. L'interface doit donc bien respecter ses points.

Exemple de site : https://figurinepop.com

### Priorité 

[BASSE]

**Comment by Florent-Deswaerte** [comment]
Evolution résolu
