### ISSUE TITLE
Fix : Note moyenne des produits

### ISSUE THREAD

**Issue by PierreKrauseEpsi** [remihamy1/webapp#21]
### Résumé : 
La note moyenne des articles ne s'affiche pas lors de la recherche.

### Reproduction : 
Faire une recherche sur la liste des produits. 

### Résultat attendu : 
Affichage de la note moyenne des produits.

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[MOYENNE]

**Comment by Florent-Deswaerte** [comment]
Fix résolu
