### ISSUE TITLE
Fix : Problème REGEX mot de passe 

### ISSUE THREAD

**Issue by PierreKrauseEpsi** [remihamy1/webapp#25]
### [Gravité] : 
Bloquant

### [Résumé] : 
Mauvais format des mots de passe enregistrés en bases.

### [Résultat attendu] : 
Modifier les mots de passe de la base de données pour les faire correspondre au regex : 
- 8 caractères minimum
- 1 majuscule minimum
- 1 chiffre minimum
- 1 caractère spécial minimum

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[BASSE]

**Comment by Florent-Deswaerte** [comment]
Fix résolu
