### ISSUE TITLE
Évolution: changement de forme sur les articles 

### ISSUE THREAD

**Issue by fortporc** [remihamy1/webapp#38]
# Évolution: changement de forme sur les articles 

## Description

**Problème constaté** : L'application a des article qui prenne trop de place et qui ne sont pas claire 

## Résultat Attendu

Modification pour mieux corespondre au standar actuelle de boutique de Ecomerce 
Changement de forme sur les articles les passer dans un format comme sous l'image

![image](https://github.com/remihamy1/webapp/assets/154219363/1cd7d39b-f4ea-472a-a23a-33742bc07657)

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[HAUTE]

**Comment by Florent-Deswaerte** [comment]
Evolution résolu
