### ISSUE TITLE
Évolution : Pagination des Produits

### ISSUE THREAD

**Issue by remihamy1** [remihamy1/webapp#4]
# Évolution : Pagination des Produits

## Description

**Fonctionnalité requise** : Mettre en place une pagination pour les produits.

## Détails

- Limiter le nombre de produits affichés par page. => la pagination 9 produits sur pc / sur mobile un scroll
- Ajouter des boutons de navigation pour les pages. =>pagination clasique en bas de page 

## Bénéfices Attendus

Meilleure performance de chargement et expérience utilisateur améliorée.

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[HAUTE]

**Comment by Florent-Deswaerte** [comment]
Fix résolu
