### ISSUE TITLE
FIX: Lien rapide non cliquable

### ISSUE THREAD

**Issue by MaXimeHH** [remihamy1/webapp#57]
### Description
les liens ne mène a rien lorsque nous cliquons sur les boutons Accueil (situé en dessous de l'input rechercher)

### Attendu 
Lorsque nous cliquons sur les boutons d'accès rapide, cela nous redirige vers la bonne page
![image](https://github.com/remihamy1/webapp/assets/116813482/137f29ef-52f2-43c4-9041-f212fccd3ef5)

**Comment by Florent-Deswaerte** [comment]
Fix résolu
