### ISSUE TITLE
Fix: bouton "Rechercher"

### ISSUE THREAD

**Issue by MaXimeHH** [remihamy1/webapp#68]
### Description 
Bouton permettant la recherche de produits.

### Problème
Lorsque nous cliquons sur le bouton "Rechercher" avec l'input vide, la liste se recharge 

### Attendue
Que le bouton "Rechercher" soit disponible seulement si l'input comporte au moins 1 caractère

**Comment by Florent-Deswaerte** [comment]
Fix résolu
