### ISSUE TITLE
Évolution : Sécurité dans l'inscription / connexion

### ISSUE THREAD

**Issue by Florent-Deswaerte** [remihamy1/webapp#8]
# Évolution sécurité dans l'inscription / connexion

## Description

**Problème constaté** : Aucune sécurité n'est mise en place durant le processus d'inscription / connexion. Modifier le système d'inscription / connexion pour ajouter des règles au niveau au mot de passe.

## Résultat Attendu

**Les règles voulus sont les suivantes** : 
- 8 caractères minimum
- 1 majuscule minimum
- 1 chiffre minimum
- 1 caractère spécial minimum

**Comment by rydward** [comment]
Branch merged, pull request validée par les 3 tech lead

**Comment by rydward** [comment]
Seulement la partie
