### ISSUE TITLE
Évolution: Ajout du nom de l'entreprise et refonte de la NavBar

### ISSUE THREAD

**Issue by MaXimeHH** [remihamy1/webapp#9]
### Description 
Ajout du nom de l'entreprise sur la plateforme.

**Contexte**
Le client souhaite un site qui vend des figurines pop. 
La cible  sont les collectionneurs, les geeks et les personnes qui aime l’art (un prochain ticket sera crée sur la mise en forme de l'interface, attente de confirmation côté client).

Le nom a ajouté est : PopStore

### NavBar
Refonte de la NavBar avec les différentes pages :
- Accueil 
- Produits
- Contact 
- Rechercher un produit
- Déconnexion / Connexion (si connecté ou déconnecté)

### Contraintes 

Aucunes contraintes côté client

### Priorité 

[BASSE]

**Comment by Florent-Deswaerte** [comment]
Fix résolu
